# Generated by Django 4.0 on 2022-02-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_watcher_alter_bid_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watch_listing',
            field=models.ManyToManyField(blank=True, related_name='watch_listings', to='auctions.Listing'),
        ),
    ]
