# Generated by Django 4.0 on 2022-02-08 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_listing_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watcher',
        ),
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writers', to='auctions.user'),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_listing', models.ManyToManyField(related_name='watch_listings', to='auctions.Listing')),
                ('watcher', models.ManyToManyField(related_name='watchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
