# Generated by Django 4.0 on 2022-03-31 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_bid_bid_alter_listing_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watch_listing',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watch_listing',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='watch_listings', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
